#
ecoinvent_caliope_regions = {
    'ALB': 'AL',
    'AUT': 'AT',
    'BEL': 'BE',
    'BGR': 'BG',
    'BIH': 'BA',
    'CHE': 'CH',
    'CYP': 'CY',
    'CZE': 'CZ',
    'DEU': 'DE',
    'DNK': 'DK',
    'ESP': 'ES',
    'EST': 'EE',
    'FIN': 'FI',
    'FRA': 'FR',
    'GBR': 'GB',
    'GRC': 'GR',
    'HRV': 'HR',
    'HUN': 'HU',
    'IRL': 'IE',
    'ISL': 'IS',
    'ITA': 'IT',
    'LTU': 'LT',
    'LUX': 'LU',
    'LVA': 'LV',
    'MKD': 'MK',
    'MNE': 'ME',
    'NLD': 'NL',
    'NOR': 'NO',
    'POL': 'PL',
    'PRT': 'PT',
    'ROU': 'RO',
    'SRB': 'RS',
    'SVK': 'SK',
    'SVN': 'SI',
    'SWE': 'SE'
}